/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './features/account/screens/SettingsScreen'
import { Route as CuentaRouteImport } from './features/account/screens/AccountScreen'
import { Route as CuentosRouteImport } from './routes/cuentos'
import { Route as EntradaRouteImport } from './features/account/screens/EntryScreen'
import { Route as VerificarRouteImport } from './features/account/screens/VerifyScreen'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminIdRouteImport } from './routes/admin.$id'
import { Route as CuentoIdRouteImport } from './routes/cuento.$id'
import { Route as FamiliaIndexRouteImport } from './features/family/screens/FamilyScreen'
import { Route as FamiliaContanosRouteImport } from './features/family/screens/TellScreen'
import { Route as FamiliaCorregirRouteImport } from './features/family/screens/CorrectScreen'
import { Route as FamiliaRevisarRouteImport } from './features/family/screens/ReviewScreen'
import { Route as JuguetesIndexRouteImport } from './routes/juguetes.index'
import { Route as JuguetesIdRouteImport } from './routes/juguetes.$id'
import { Route as IdeaIdIndexRouteImport } from './routes/idea.$id.index'
import { Route as IdeaIdRelojRouteImport } from './routes/idea.$id.reloj'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
})
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
})
const CuentosRoute = CuentosRouteImport.update({
  id: '/cuentos',
  path: '/cuentos',
  getParentRoute: () => rootRouteImport,
})
const EntradaRoute = EntradaRouteImport.update({
  id: '/entrada',
  path: '/entrada',
  getParentRoute: () => rootRouteImport,
})
const VerificarRoute = VerificarRouteImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => rootRouteImport,
})
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
})
const AdminIdRoute = AdminIdRouteImport.update({
  id: '/admin/$id',
  path: '/admin/$id',
  getParentRoute: () => rootRouteImport,
})
const CuentoIdRoute = CuentoIdRouteImport.update({
  id: '/cuento/$id',
  path: '/cuento/$id',
  getParentRoute: () => rootRouteImport,
})
const FamiliaIndexRoute = FamiliaIndexRouteImport.update({
  id: '/familia/',
  path: '/familia/',
  getParentRoute: () => rootRouteImport,
})
const FamiliaContanosRoute = FamiliaContanosRouteImport.update({
  id: '/familia/contanos',
  path: '/familia/contanos',
  getParentRoute: () => rootRouteImport,
})
const FamiliaCorregirRoute = FamiliaCorregirRouteImport.update({
  id: '/familia/corregir',
  path: '/familia/corregir',
  getParentRoute: () => rootRouteImport,
})
const FamiliaRevisarRoute = FamiliaRevisarRouteImport.update({
  id: '/familia/revisar',
  path: '/familia/revisar',
  getParentRoute: () => rootRouteImport,
})
const JuguetesIndexRoute = JuguetesIndexRouteImport.update({
  id: '/juguetes/',
  path: '/juguetes/',
  getParentRoute: () => rootRouteImport,
})
const JuguetesIdRoute = JuguetesIdRouteImport.update({
  id: '/juguetes/$id',
  path: '/juguetes/$id',
  getParentRoute: () => rootRouteImport,
})
const IdeaIdIndexRoute = IdeaIdIndexRouteImport.update({
  id: '/idea/$id/',
  path: '/idea/$id/',
  getParentRoute: () => rootRouteImport,
})
const IdeaIdRelojRoute = IdeaIdRelojRouteImport.update({
  id: '/idea/$id/reloj',
  path: '/idea/$id/reloj',
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  CuentaRoute: CuentaRoute,
  CuentosRoute: CuentosRoute,
  EntradaRoute: EntradaRoute,
  VerificarRoute: VerificarRoute,
  AdminIdRoute: AdminIdRoute,
  CuentoIdRoute: CuentoIdRoute,
  FamiliaContanosRoute: FamiliaContanosRoute,
  FamiliaCorregirRoute: FamiliaCorregirRoute,
  FamiliaRevisarRoute: FamiliaRevisarRoute,
  JuguetesIdRoute: JuguetesIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  FamiliaIndexRoute: FamiliaIndexRoute,
  JuguetesIndexRoute: JuguetesIndexRoute,
  IdeaIdRelojRoute: IdeaIdRelojRoute,
  IdeaIdIndexRoute: IdeaIdIndexRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
