/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CuentosRouteImport } from './routes/cuentos'
import { Route as CuentoIdRouteImport } from './routes/cuento.$id'
import { Route as IdeaIdRouteImport } from './routes/idea.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentosRoute = CuentosRouteImport.update({
  id: '/cuentos',
  path: '/cuentos',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentoIdRoute = CuentoIdRouteImport.update({
  id: '/cuento/$id',
  path: '/cuento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeaIdRoute = IdeaIdRouteImport.update({
  id: '/idea/$id',
  path: '/idea/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cuentos': typeof CuentosRoute
  '/cuento/$id': typeof CuentoIdRoute
  '/idea/$id': typeof IdeaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuentos': typeof CuentosRoute
  '/cuento/$id': typeof CuentoIdRoute
  '/idea/$id': typeof IdeaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cuentos': typeof CuentosRoute
  '/cuento/$id': typeof CuentoIdRoute
  '/idea/$id': typeof IdeaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cuentos' | '/cuento/$id' | '/idea/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cuentos' | '/cuento/$id' | '/idea/$id'
  id: '__root__' | '/' | '/cuentos' | '/cuento/$id' | '/idea/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuentosRoute: typeof CuentosRoute
  CuentoIdRoute: typeof CuentoIdRoute
  IdeaIdRoute: typeof IdeaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuentos': {
      id: '/cuentos'
      path: '/cuentos'
      fullPath: '/cuentos'
      preLoaderRoute: typeof CuentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuento/$id': {
      id: '/cuento/$id'
      path: '/cuento/$id'
      fullPath: '/cuento/$id'
      preLoaderRoute: typeof CuentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idea/$id': {
      id: '/idea/$id'
      path: '/idea/$id'
      fullPath: '/idea/$id'
      preLoaderRoute: typeof IdeaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuentosRoute: CuentosRoute,
  CuentoIdRoute: CuentoIdRoute,
  IdeaIdRoute: IdeaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
