/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as CuentosRouteImport } from './routes/cuentos'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as EntradaRouteImport } from './routes/entrada'
import { Route as VerificarRouteImport } from './routes/verificar'
import { Route as CuentoIdRouteImport } from './routes/cuento.$id'
import { Route as FamiliaIndexRouteImport } from './routes/familia.index'
import { Route as FamiliaContanosRouteImport } from './routes/familia.contanos'
import { Route as FamiliaCorregirRouteImport } from './routes/familia.corregir'
import { Route as FamiliaRevisarRouteImport } from './routes/familia.revisar'
import { Route as IdeaIdIndexRouteImport } from './routes/idea.$id.index'
import { Route as IdeaIdRelojRouteImport } from './routes/idea.$id.reloj'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
})
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
})
const CuentosRoute = CuentosRouteImport.update({
  id: '/cuentos',
  path: '/cuentos',
  getParentRoute: () => rootRouteImport,
})
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
})
const EntradaRoute = EntradaRouteImport.update({
  id: '/entrada',
  path: '/entrada',
  getParentRoute: () => rootRouteImport,
})
const VerificarRoute = VerificarRouteImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => rootRouteImport,
})
const CuentoIdRoute = CuentoIdRouteImport.update({
  id: '/cuento/$id',
  path: '/cuento/$id',
  getParentRoute: () => rootRouteImport,
})
const FamiliaIndexRoute = FamiliaIndexRouteImport.update({
  id: '/familia/',
  path: '/familia/',
  getParentRoute: () => rootRouteImport,
})
const FamiliaContanosRoute = FamiliaContanosRouteImport.update({
  id: '/familia/contanos',
  path: '/familia/contanos',
  getParentRoute: () => rootRouteImport,
})
const FamiliaCorregirRoute = FamiliaCorregirRouteImport.update({
  id: '/familia/corregir',
  path: '/familia/corregir',
  getParentRoute: () => rootRouteImport,
})
const FamiliaRevisarRoute = FamiliaRevisarRouteImport.update({
  id: '/familia/revisar',
  path: '/familia/revisar',
  getParentRoute: () => rootRouteImport,
})
const IdeaIdIndexRoute = IdeaIdIndexRouteImport.update({
  id: '/idea/$id/',
  path: '/idea/$id/',
  getParentRoute: () => rootRouteImport,
})
const IdeaIdRelojRoute = IdeaIdRelojRouteImport.update({
  id: '/idea/$id/reloj',
  path: '/idea/$id/reloj',
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  CuentaRoute: CuentaRoute,
  CuentosRoute: CuentosRoute,
  DemoRoute: DemoRoute,
  EntradaRoute: EntradaRoute,
  VerificarRoute: VerificarRoute,
  CuentoIdRoute: CuentoIdRoute,
  FamiliaContanosRoute: FamiliaContanosRoute,
  FamiliaCorregirRoute: FamiliaCorregirRoute,
  FamiliaRevisarRoute: FamiliaRevisarRoute,
  FamiliaIndexRoute: FamiliaIndexRoute,
  IdeaIdRelojRoute: IdeaIdRelojRoute,
  IdeaIdIndexRoute: IdeaIdIndexRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
