/**
 * The first activity templates, loaded by the catalog seed on every
 * `docker compose up`. A template already in the database is never
 * overwritten: the database is the catalog's home, so change a loaded
 * template there.
 *
 * Slots ({kid}, {pet}, {toy}, {toy2}, {toy3}, {interest}) are filled with the
 * family's words. 0.1 knows toys only by name, so a template can't assume
 * what a toy is, and nothing may agree in gender with a slot ("cuando
 * aparezca", not "cuando lo encuentre"). Write "a {toy}" and "de {toy}"
 * freely: they contract to "al" and "del".
 *
 * Pending Alex's review and a voice pass (JUG-14).
 */

/** @type {import('../../src/activities/activities.service.js').ActivityTemplateInput[]} */
export const activityTemplates = [
  {
    slug: 'la-busqueda',
    title: 'La búsqueda de {toy}',
    minutes: 15,
    place: 'indoor',
    minAgeMonths: 12,
    maxAgeMonths: 47,
    energy: 'medium',
    categories: ['pretend'],
    smallSpace: true,
    materials: ['un almohadón'],
    skills: ['permanencia del objeto', 'lenguaje'],
    safety: ['El juguete tiene que ser más grande que la boca del chico.'],
    why: 'Usa {toy}, y a esta edad pocas cosas divierten más que esconder y encontrar. Ideal para una tarde adentro.',
    needs: '{toy} y un almohadón.',
    steps: [
      'Escondé {toy} debajo de un almohadón mientras {kid} mira.',
      'Preguntá: “¿Dónde está?” y busquen juntos.',
      'Cuando aparezca, ¡festejen con un grito de alegría!',
    ],
    easier: 'Dejá una parte asomando.',
    harder: 'Escondé {toy} en otro lugar del living.',
  },
  {
    slug: 'tren-de-almohadones',
    title: 'Un tren de almohadones',
    minutes: 20,
    place: 'indoor',
    minAgeMonths: 18,
    maxAgeMonths: 59,
    energy: 'medium',
    categories: ['pretend', 'move'],
    smallSpace: false,
    materials: ['almohadones'],
    skills: ['juego simbólico', 'turnos'],
    safety: [],
    why: '{toy} y {toy2} viajan de pasajeros, y {kid} maneja el tren.',
    needs: 'unos almohadones en fila, {toy} y {toy2}.',
    steps: [
      'Pongan los almohadones en fila: esa es la vía, y también el tren.',
      'Suban a {toy} y a {toy2} como pasajeros.',
      'En cada parada, preguntá: “¿Quién se baja acá?” y hagan juntos el ruido de ese pasajero.',
    ],
    easier: 'Un solo pasajero y un viaje corto.',
    harder: 'Inventen paradas con cosas que le encantan a {kid}, como {interest}.',
  },
  {
    slug: 'hora-de-comer',
    title: '{toy} tiene hambre',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 12,
    maxAgeMonths: 47,
    energy: 'low',
    categories: ['pretend', 'low_energy'],
    smallSpace: true,
    materials: ['un plato', 'una cuchara de plástico'],
    skills: ['juego simbólico', 'motricidad fina', 'cuidar a otro'],
    safety: [],
    why: 'Un juego tranquilo con {toy}, para bajar un cambio antes de la cena.',
    needs: '{toy}, un plato y una cuchara de plástico.',
    steps: [
      'Sentá a {toy} en un almohadón y contale a {kid} que tiene mucha hambre.',
      'Dale a {kid} el plato y la cuchara para que le dé de comer.',
      'Cuando termine, hagan “shh” y acuesten a {toy} a dormir.',
    ],
    easier: 'Dale vos la primera cucharada y que {kid} te copie.',
    harder: 'Que {kid} cuente qué le está dando de comer.',
  },
  {
    slug: 'galope-en-la-plaza',
    title: 'Galope en la plaza',
    minutes: 20,
    place: 'outdoor',
    minAgeMonths: 18,
    maxAgeMonths: 71,
    energy: 'high',
    categories: ['move', 'explore'],
    smallSpace: false,
    materials: [],
    skills: ['motricidad gruesa', 'seguir consignas'],
    safety: ['Galopen lejos de la calle y de las hamacas en movimiento.'],
    why: 'En la plaza hay lugar de sobra para galopar, y {pet} se suma a la carrera.',
    needs: 'nada más que la plaza.',
    steps: [
      'Galopen juntos hasta el primer árbol, haciendo “clop, clop”.',
      'En cada árbol, frenen y relinchen bien fuerte.',
      'Que {kid} elija el próximo árbol, y {pet} los sigue.',
    ],
    easier: 'Vayan al paso, de la mano.',
    harder: 'Que {kid} diga cuándo se galopa y cuándo se frena.',
  },

  // Batch 1: pretend and create (JUG-78).
  {
    slug: 'el-cumple',
    title: 'El cumple de {toy}',
    minutes: 15,
    place: 'indoor',
    minAgeMonths: 18,
    maxAgeMonths: 47,
    energy: 'medium',
    categories: ['pretend'],
    smallSpace: true,
    materials: ['un vaso de plástico o un tupper', 'un repasador'],
    skills: ['juego simbólico', 'lenguaje', 'esperar el turno'],
    safety: ['La vela es de mentira: un dedo parado arriba de la torta. Nada de fósforos.'],
    why: 'Hoy cumple años {toy}. A esta edad un cumple es lo más, aunque la torta sea de mentira.',
    needs: '{toy}, {toy2}, un vaso de plástico dado vuelta y un repasador.',
    steps: [
      'Sienten a {toy} en el centro y a {toy2} al lado. Si {pet} anda cerca, que se sume.',
      'Pongan la torta, que es el vaso dado vuelta, con un dedo de vela, y canten el feliz cumpleaños.',
      'Que {kid} sople la vela y le dé a {toy} un regalo envuelto en el repasador.',
    ],
    easier: 'Sin regalo: soplar la vela y aplaudir ya es la fiesta entera.',
    harder: 'Que {kid} envuelva el regalo y te haga adivinar qué hay adentro.',
  },
  {
    slug: 'el-consultorio',
    title: '{toy} va al médico',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 18,
    maxAgeMonths: 47,
    energy: 'low',
    categories: ['pretend', 'low_energy'],
    smallSpace: true,
    materials: ['una cuchara', 'cinta de papel'],
    skills: ['juego simbólico', 'cuidar a otro', 'lenguaje'],
    safety: ['Cortá vos la cinta, y al terminar junten los pedacitos: no van a la boca.'],
    why: '{toy} no se siente bien, y {kid} atiende en el consultorio. Jugar a curar ayuda a perderle el miedo al pediatra.',
    needs: '{toy}, una cuchara y un poco de cinta de papel.',
    steps: [
      'Contale a {kid} que {toy} se siente mal y viene al consultorio.',
      'Que {kid} use la cuchara para escuchar a {toy} y tomarle la fiebre.',
      'Pongan una curita de cinta donde {kid} diga, y un abrazo para que se cure.',
    ],
    easier: 'Atendé vos primero, y que {kid} te copie.',
    harder: 'Que {kid} te pregunte qué le duele a {toy} y le recete algo.',
  },
  {
    slug: 'como-hace-la-mascota',
    title: '¿Cómo hace {pet}?',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 12,
    maxAgeMonths: 47,
    energy: 'medium',
    categories: ['pretend', 'move'],
    smallSpace: true,
    materials: [],
    skills: ['imitación', 'observar', 'motricidad gruesa'],
    safety: ['Despejen el piso antes de empezar, y ojo con las esquinas de la mesa.'],
    why: '{kid} conoce a {pet} de memoria. Imitar cómo camina, come y duerme es teatro puro, y no hace falta nada.',
    needs: 'nada más que un poco de lugar en el piso.',
    steps: [
      'Preguntale a {kid}: “¿Cómo camina {pet}?”, y háganlo juntos por el living.',
      'Sigan con el ruido que hace {pet}, y con cómo come.',
      'Terminen con la siesta de {pet}: los dos quietos en el piso, hasta que alguien ronque.',
    ],
    easier: 'Hacelo vos primero, y que {kid} te copie.',
    harder: 'Que {kid} haga algo de {pet} sin decir qué, y vos tratá de adivinar.',
  },
  {
    slug: 'el-almacen',
    title: 'El almacén de {toy}',
    minutes: 15,
    place: 'indoor',
    minAgeMonths: 18,
    maxAgeMonths: 47,
    energy: 'low',
    categories: ['pretend'],
    smallSpace: true,
    materials: ['tres o cuatro cosas de la alacena', 'una bolsa'],
    skills: ['juego simbólico', 'lenguaje', 'turnos'],
    safety: ['Nada de vidrio, ni cosas tan chicas que entren en la boca.'],
    why: 'Hacer las compras es algo que {kid} ve todos los días. Hoy {toy} atiende el almacén, y {kid} compra.',
    needs: '{toy}, una bolsa y tres o cuatro cosas de la alacena, como un paquete de fideos o una lata.',
    steps: [
      'Pongan las cosas de la alacena en fila, y a {toy} atrás del mostrador.',
      'Que {kid} pida algo. Vos hablás por {toy}: “¿Qué va a llevar?”.',
      'Se paga con un aplauso, y la compra va a la bolsa. Después cambian, y atiende {kid}.',
    ],
    easier: 'Una sola cosa por vez, y alcanza con dar y decir “gracias”.',
    harder: 'Que {kid} compre dos cosas y cuente cuántas lleva.',
  },
  {
    slug: 'ring-ring',
    title: 'Ring, ring: llama {toy}',
    minutes: 5,
    place: 'indoor',
    minAgeMonths: 15,
    maxAgeMonths: 47,
    energy: 'low',
    categories: ['pretend', 'low_energy'],
    smallSpace: true,
    materials: ['una banana, o cualquier cosa que haga de teléfono'],
    skills: ['lenguaje', 'juego simbólico', 'turnos'],
    safety: [],
    why: 'Cinco minutos y una banana: ideal para cuando no da para más. {toy} tiene muchas ganas de hablar con {kid}.',
    needs: 'una banana, o cualquier cosa que haga de teléfono.',
    steps: [
      'Hacé sonar la banana: “¡Ring, ring!”. Atendé, y decí que es para {kid}.',
      'Pasale el teléfono: es {toy}, que quiere saber qué hizo {kid} hoy.',
      'Ahora que {kid} llame a quien quiera, y vos atendés.',
    ],
    easier: 'Vos hablás por {toy}; a {kid} le alcanza con escuchar.',
    harder: 'Que {kid} le cuente a {toy} algo que pasó hoy, con todos los detalles.',
  },
  {
    slug: 'la-cueva',
    title: 'Una cueva para {toy}',
    minutes: 20,
    place: 'indoor',
    minAgeMonths: 12,
    maxAgeMonths: 47,
    energy: 'low',
    categories: ['pretend', 'low_energy'],
    smallSpace: true,
    materials: ['una sábana o una manta', 'la mesa o dos sillas firmes'],
    skills: ['juego simbólico', 'lenguaje', 'turnos'],
    safety: [
      'Que la manta no quede suelta sobre la cara de nadie: los más chicos se enredan.',
      'Si usan sillas, que sean firmes y no se vuelquen al tirar de la manta.',
    ],
    why: 'Abajo de una manta todo parece un secreto. {toy} y {toy2} se mudan a la cueva, y {kid} les muestra todo.',
    needs: 'una sábana o una manta, la mesa, {toy} y {toy2}.',
    steps: [
      'Tiren la manta sobre la mesa hasta que llegue al piso: esa es la cueva.',
      'Entren con {toy} y {toy2}, y cuéntense secretos bien bajito.',
      'Salí, golpeá la manta y que {kid} pregunte: “¿Quién es?”. Solo entrás con la contraseña.',
    ],
    easier: 'Una manta sobre tus rodillas, con vos en el piso, ya es una cueva.',
    harder: 'Que {kid} invente la contraseña y decida quién entra a la cueva.',
  },
  {
    slug: 'el-retrato',
    title: 'El retrato de {toy}',
    minutes: 15,
    place: 'indoor',
    minAgeMonths: 18,
    maxAgeMonths: 47,
    energy: 'low',
    categories: ['create'],
    smallSpace: true,
    materials: ['una hoja grande o un cartón abierto', 'crayones gruesos'],
    skills: ['motricidad fina', 'reconocer formas', 'creatividad'],
    safety: ['Crayones gruesos, y con los más chicos, atentos a que no vayan a la boca.'],
    why: '{toy} posa, vos dibujás el contorno y {kid} pinta el retrato. Queda uno para pegar en la heladera.',
    needs: '{toy}, una hoja grande o un cartón abierto, y crayones gruesos.',
    steps: [
      'Acuesten a {toy} sobre la hoja, y dibujá el contorno despacito.',
      'Saquen a {toy}, miren la forma y pregunten: “¿Quién es?”.',
      'Que {kid} pinte el retrato con los colores que quiera.',
    ],
    easier: 'Que {kid} haga garabatos adentro del contorno; no hace falta nada más.',
    harder: 'Que {kid} dibuje al lado algo que le encanta, como {interest}.',
  },
  {
    slug: 'la-orquesta',
    title: 'La orquesta de la cocina',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 12,
    maxAgeMonths: 47,
    energy: 'high',
    categories: ['create'],
    smallSpace: true,
    materials: ['un par de ollas o tuppers vacíos', 'dos cucharas de madera'],
    skills: ['ritmo', 'escuchar', 'causa y efecto'],
    safety: ['Ollas frías y vacías, y lejos de la cocina encendida.'],
    why: 'Un rato de ruido permitido: {kid} toca, vos acompañás, y después la casa queda más tranquila.',
    needs: 'un par de ollas o tuppers vacíos, y dos cucharas de madera.',
    steps: [
      'Den vuelta las ollas en el piso y repartan las cucharas.',
      'Toquen juntos: primero fuerte, después bajito, bajito.',
      'Cuando vos parás, {kid} para. Y arrancan de nuevo.',
    ],
    easier: 'Que {kid} toque como quiera, y vos acompañás con aplausos.',
    harder: 'Tocá un ritmo corto, tan-tan-tan, y que {kid} lo repita.',
  },
  {
    slug: 'una-torre',
    title: 'Una torre para {toy}',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 12,
    maxAgeMonths: 47,
    energy: 'medium',
    categories: ['create'],
    smallSpace: true,
    materials: ['vasos de plástico o tuppers'],
    skills: ['motricidad fina', 'equilibrio', 'causa y efecto'],
    safety: ['Solo plástico: nada de vidrio ni loza.'],
    why: 'Construir y tirar abajo es de lo más divertido a esta edad. Y arriba de todo, en el lugar de honor, va {toy}.',
    needs: 'unos vasos de plástico o tuppers, y {toy}.',
    steps: [
      'Apilen los vasos juntos, uno arriba del otro.',
      'Cuando la torre esté alta, pongan a {toy} arriba de todo.',
      'A la cuenta de tres, que {kid} la tire abajo. Y a construir de nuevo.',
    ],
    easier: 'Con dos o tres tuppers grandes alcanza para una torre.',
    harder: 'Que {kid} construya sin ayuda y cuente los pisos.',
  },
  {
    slug: 'la-casa-de-carton',
    title: 'La casa de {toy}',
    minutes: 25,
    place: 'indoor',
    minAgeMonths: 18,
    maxAgeMonths: 47,
    energy: 'low',
    categories: ['create', 'pretend'],
    smallSpace: true,
    materials: ['una caja de cartón', 'crayones gruesos', 'una tijera, solo para vos'],
    skills: ['creatividad', 'motricidad fina', 'juego simbólico'],
    safety: [
      'Sacale a la caja las grampas y la cinta de embalar antes de jugar.',
      'La tijera la usás vos, y después se guarda.',
    ],
    why: 'Con una caja vacía alcanza: {toy} se muda a una casa nueva, y {kid} la decora.',
    needs: 'una caja de cartón, crayones gruesos, una tijera y {toy}.',
    steps: [
      'Recortá en la caja una puerta y una ventana.',
      'Que {kid} pinte la casa por fuera: rayas, flores, lo que salga.',
      'Que {toy} entre por la puerta y se asome por la ventana a saludar.',
    ],
    easier: 'Sin recortar nada: la caja abierta ya es una casa.',
    harder: 'Que {kid} le arme a {toy} una cama adentro, con un repasador.',
  },
  {
    slug: 'el-camino',
    title: 'Un camino para {toy}',
    minutes: 15,
    place: 'indoor',
    minAgeMonths: 18,
    maxAgeMonths: 47,
    energy: 'medium',
    categories: ['create', 'pretend'],
    smallSpace: true,
    materials: ['cinta de papel'],
    skills: ['motricidad fina', 'planificar', 'juego simbólico'],
    safety: [
      'Cortá vos la cinta, y al terminar junten los pedacitos: no van a la boca.',
      'Mejor sobre baldosas o cerámica: en la madera, la cinta puede dejar marca.',
    ],
    why: 'Una tira de cinta en el piso se vuelve un camino, y {toy} tiene que llegar a algún lado. {kid} decide adónde.',
    needs: 'cinta de papel y {toy}.',
    steps: [
      'Pegá una tira larga de cinta en el piso, con curvas, y que {kid} te ayude a apretarla.',
      'Al final del camino, marquen una casita con un cuadrado de cinta.',
      'Que {kid} lleve a {toy} por el camino hasta la casita, sin salirse.',
    ],
    easier: 'Un camino recto y corto, de la mesa a la puerta.',
    harder: 'Agreguen un puente, que es un almohadón, y un túnel, que es una silla.',
  },
]
