/**
 * The activity templates, loaded by the catalog seed on every
 * `docker compose up`. A template already in the database is never
 * overwritten: the database is the catalog's home, so change a loaded
 * template there.
 *
 * Slots ({kid}, {pet}, {toy}, {toy2}, {toy3}, {interest}) are filled with the
 * family's words. The catalog knows toys only by name, so a template can't
 * assume what a toy is, and nothing may agree in gender with a slot ("cuando
 * aparezca", not "cuando lo encuentre"; "que lo elija {kid}", not "que {kid}
 * esté cansado"). Write "a {toy}" and "de {toy}" freely: they contract to
 * "al" and "del".
 *
 * Batches 2 to 8 (JUG-24) cover ages 3 to 5, which batch 1 barely reached,
 * and the categories it never used: learn, helpers and out_and_about. They
 * are longer where the age allows it, up to six steps, and most need no toy,
 * so they reach families with a small toy box. The ideas are adapted from
 * published activity guides, not copied: Zero to Three's play activities for
 * 12-24 and 24-36 months, Montessori practical-life lists, preschool
 * activity and nature-play roundups, and the traditional games children in
 * Buenos Aires already play (la mancha, la rayuela, la gallinita ciega,
 * Antón Pirulero). Every one was rewritten for a Buenos Aires home, with
 * what is actually in the kitchen, the safety rules the original left out,
 * and the age range this catalog uses.
 *
 * Pending Alex's review and a voice pass (JUG-14).
 */

/** @type {import('../../src/catalog/catalog.service.js').ActivityTemplateInput[]} */
export const activityTemplates = [
  {
    slug: 'la-busqueda',
    title: 'La búsqueda de {toy}',
    minutes: 15,
    place: 'indoor',
    minAgeMonths: 12,
    maxAgeMonths: 47,
    energy: 'medium',
    categories: ['pretend'],
    smallSpace: true,
    materials: ['un almohadón'],
    skills: ['permanencia del objeto', 'lenguaje'],
    safety: ['El juguete tiene que ser más grande que la boca del chico.'],
    why: 'Usa {toy}, y a esta edad pocas cosas divierten más que esconder y encontrar. Ideal para una tarde adentro.',
    needs: '{toy} y un almohadón.',
    steps: [
      'Escondé {toy} debajo de un almohadón mientras {kid} mira.',
      'Preguntá: “¿Dónde está?” y busquen juntos.',
      'Cuando aparezca, ¡festejen con un grito de alegría!',
    ],
    easier: 'Dejá una parte asomando.',
    harder: 'Escondé {toy} en otro lugar del living.',
  },
  {
    slug: 'tren-de-almohadones',
    title: 'Un tren de almohadones',
    minutes: 20,
    place: 'indoor',
    minAgeMonths: 18,
    maxAgeMonths: 59,
    energy: 'medium',
    categories: ['pretend', 'move'],
    smallSpace: false,
    materials: ['almohadones'],
    skills: ['juego simbólico', 'turnos'],
    safety: [],
    why: '{toy} y {toy2} viajan de pasajeros, y {kid} maneja el tren.',
    needs: 'unos almohadones en fila, {toy} y {toy2}.',
    steps: [
      'Pongan los almohadones en fila: esa es la vía, y también el tren.',
      'Suban a {toy} y a {toy2} como pasajeros.',
      'En cada parada, preguntá: “¿Quién se baja acá?” y hagan juntos el ruido de ese pasajero.',
    ],
    easier: 'Un solo pasajero y un viaje corto.',
    harder: 'Inventen paradas con cosas que le encantan a {kid}, como {interest}.',
  },
  {
    slug: 'hora-de-comer',
    title: '{toy} tiene hambre',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 12,
    maxAgeMonths: 47,
    energy: 'low',
    categories: ['pretend', 'low_energy'],
    smallSpace: true,
    materials: ['un plato', 'una cuchara de plástico'],
    skills: ['juego simbólico', 'motricidad fina', 'cuidar a otro'],
    safety: [],
    why: 'Un juego tranquilo con {toy}, para bajar un cambio antes de la cena.',
    needs: '{toy}, un plato y una cuchara de plástico.',
    steps: [
      'Sentá a {toy} en un almohadón y contale a {kid} que tiene mucha hambre.',
      'Dale a {kid} el plato y la cuchara para que le dé de comer.',
      'Cuando termine, hagan “shh” y acuesten a {toy} a dormir.',
    ],
    easier: 'Dale vos la primera cucharada y que {kid} te copie.',
    harder: 'Que {kid} cuente qué le está dando de comer.',
  },
  {
    slug: 'galope-en-la-plaza',
    title: 'Galope en la plaza',
    minutes: 20,
    place: 'outdoor',
    minAgeMonths: 18,
    maxAgeMonths: 71,
    energy: 'high',
    categories: ['move', 'explore'],
    smallSpace: false,
    materials: [],
    skills: ['motricidad gruesa', 'seguir consignas'],
    safety: ['Galopen lejos de la calle y de las hamacas en movimiento.'],
    why: 'En la plaza hay lugar de sobra para galopar, y {pet} se suma a la carrera.',
    needs: 'nada más que la plaza.',
    steps: [
      'Galopen juntos hasta el primer árbol, haciendo “clop, clop”.',
      'En cada árbol, frenen y relinchen bien fuerte.',
      'Que {kid} elija el próximo árbol, y {pet} los sigue.',
    ],
    easier: 'Vayan al paso, de la mano.',
    harder: 'Que {kid} diga cuándo se galopa y cuándo se frena.',
  },

  // Batch 1: pretend and create (JUG-78).
  {
    slug: 'el-cumple',
    title: 'El cumple de {toy}',
    minutes: 15,
    place: 'indoor',
    minAgeMonths: 18,
    maxAgeMonths: 47,
    energy: 'medium',
    categories: ['pretend'],
    smallSpace: true,
    materials: ['un vaso de plástico o un tupper', 'un repasador'],
    skills: ['juego simbólico', 'lenguaje', 'esperar el turno'],
    safety: ['La vela es de mentira: un dedo parado arriba de la torta. Nada de fósforos.'],
    why: 'Hoy cumple años {toy}. A esta edad un cumple es lo más, aunque la torta sea de mentira.',
    needs: '{toy}, {toy2}, un vaso de plástico dado vuelta y un repasador.',
    steps: [
      'Sienten a {toy} en el centro y a {toy2} al lado. Si {pet} anda cerca, que se sume.',
      'Pongan la torta, que es el vaso dado vuelta, con un dedo de vela, y canten el feliz cumpleaños.',
      'Que {kid} sople la vela y le dé a {toy} un regalo envuelto en el repasador.',
    ],
    easier: 'Sin regalo: soplar la vela y aplaudir ya es la fiesta entera.',
    harder: 'Que {kid} envuelva el regalo y te haga adivinar qué hay adentro.',
  },
  {
    slug: 'el-consultorio',
    title: '{toy} va al médico',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 18,
    maxAgeMonths: 47,
    energy: 'low',
    categories: ['pretend', 'low_energy'],
    smallSpace: true,
    materials: ['una cuchara', 'cinta de papel'],
    skills: ['juego simbólico', 'cuidar a otro', 'lenguaje'],
    safety: ['Cortá vos la cinta, y al terminar junten los pedacitos: no van a la boca.'],
    why: '{toy} no se siente bien, y {kid} atiende en el consultorio. Jugar a curar ayuda a perderle el miedo al pediatra.',
    needs: '{toy}, una cuchara y un poco de cinta de papel.',
    steps: [
      'Contale a {kid} que {toy} se siente mal y viene al consultorio.',
      'Que {kid} use la cuchara para escuchar a {toy} y tomarle la fiebre.',
      'Pongan una curita de cinta donde {kid} diga, y un abrazo para que se cure.',
    ],
    easier: 'Atendé vos primero, y que {kid} te copie.',
    harder: 'Que {kid} te pregunte qué le duele a {toy} y le recete algo.',
  },
  {
    slug: 'como-hace-la-mascota',
    title: '¿Cómo hace {pet}?',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 12,
    maxAgeMonths: 47,
    energy: 'medium',
    categories: ['pretend', 'move'],
    smallSpace: true,
    materials: [],
    skills: ['imitación', 'observar', 'motricidad gruesa'],
    safety: ['Despejen el piso antes de empezar, y ojo con las esquinas de la mesa.'],
    why: '{kid} conoce a {pet} de memoria. Imitar cómo camina, come y duerme es teatro puro, y no hace falta nada.',
    needs: 'nada más que un poco de lugar en el piso.',
    steps: [
      'Preguntale a {kid}: “¿Cómo camina {pet}?”, y háganlo juntos por el living.',
      'Sigan con el ruido que hace {pet}, y con cómo come.',
      'Terminen con la siesta de {pet}: los dos quietos en el piso, hasta que alguien ronque.',
    ],
    easier: 'Hacelo vos primero, y que {kid} te copie.',
    harder: 'Que {kid} haga algo de {pet} sin decir qué, y vos tratá de adivinar.',
  },
  {
    slug: 'el-almacen',
    title: 'El almacén de {toy}',
    minutes: 15,
    place: 'indoor',
    minAgeMonths: 18,
    maxAgeMonths: 47,
    energy: 'low',
    categories: ['pretend'],
    smallSpace: true,
    materials: ['tres o cuatro cosas de la alacena', 'una bolsa'],
    skills: ['juego simbólico', 'lenguaje', 'turnos'],
    safety: ['Nada de vidrio, ni cosas tan chicas que entren en la boca.'],
    why: 'Hacer las compras es algo que {kid} ve todos los días. Hoy {toy} atiende el almacén, y {kid} compra.',
    needs: '{toy}, una bolsa y tres o cuatro cosas de la alacena, como un paquete de fideos o una lata.',
    steps: [
      'Pongan las cosas de la alacena en fila, y a {toy} atrás del mostrador.',
      'Que {kid} pida algo. Vos hablás por {toy}: “¿Qué va a llevar?”.',
      'Se paga con un aplauso, y la compra va a la bolsa. Después cambian, y atiende {kid}.',
    ],
    easier: 'Una sola cosa por vez, y alcanza con dar y decir “gracias”.',
    harder: 'Que {kid} compre dos cosas y cuente cuántas lleva.',
  },
  {
    slug: 'ring-ring',
    title: 'Ring, ring: llama {toy}',
    minutes: 5,
    place: 'indoor',
    minAgeMonths: 15,
    maxAgeMonths: 47,
    energy: 'low',
    categories: ['pretend', 'low_energy'],
    smallSpace: true,
    materials: ['una banana, o cualquier cosa que haga de teléfono'],
    skills: ['lenguaje', 'juego simbólico', 'turnos'],
    safety: [],
    why: 'Cinco minutos y una banana: ideal para cuando no da para más. {toy} tiene muchas ganas de hablar con {kid}.',
    needs: 'una banana, o cualquier cosa que haga de teléfono.',
    steps: [
      'Hacé sonar la banana: “¡Ring, ring!”. Atendé, y decí que es para {kid}.',
      'Pasale el teléfono: es {toy}, que quiere saber qué hizo {kid} hoy.',
      'Ahora que {kid} llame a quien quiera, y vos atendés.',
    ],
    easier: 'Vos hablás por {toy}; a {kid} le alcanza con escuchar.',
    harder: 'Que {kid} le cuente a {toy} algo que pasó hoy, con todos los detalles.',
  },
  {
    slug: 'la-cueva',
    title: 'Una cueva para {toy}',
    minutes: 20,
    place: 'indoor',
    minAgeMonths: 12,
    maxAgeMonths: 47,
    energy: 'low',
    categories: ['pretend', 'low_energy'],
    smallSpace: true,
    materials: ['una sábana o una manta', 'la mesa o dos sillas firmes'],
    skills: ['juego simbólico', 'lenguaje', 'turnos'],
    safety: [
      'Que la manta no quede suelta sobre la cara de nadie: los más chicos se enredan.',
      'Si usan sillas, que sean firmes y no se vuelquen al tirar de la manta.',
    ],
    why: 'Abajo de una manta todo parece un secreto. {toy} y {toy2} se mudan a la cueva, y {kid} les muestra todo.',
    needs: 'una sábana o una manta, la mesa, {toy} y {toy2}.',
    steps: [
      'Tiren la manta sobre la mesa hasta que llegue al piso: esa es la cueva.',
      'Entren con {toy} y {toy2}, y cuéntense secretos bien bajito.',
      'Salí, golpeá la manta y que {kid} pregunte: “¿Quién es?”. Solo entrás con la contraseña.',
    ],
    easier: 'Una manta sobre tus rodillas, con vos en el piso, ya es una cueva.',
    harder: 'Que {kid} invente la contraseña y decida quién entra a la cueva.',
  },
  {
    slug: 'el-retrato',
    title: 'El retrato de {toy}',
    minutes: 15,
    place: 'indoor',
    minAgeMonths: 18,
    maxAgeMonths: 47,
    energy: 'low',
    categories: ['create'],
    smallSpace: true,
    materials: ['una hoja grande o un cartón abierto', 'crayones gruesos'],
    skills: ['motricidad fina', 'reconocer formas', 'creatividad'],
    safety: ['Crayones gruesos, y con los más chicos, atentos a que no vayan a la boca.'],
    why: '{toy} posa, vos dibujás el contorno y {kid} pinta el retrato. Queda uno para pegar en la heladera.',
    needs: '{toy}, una hoja grande o un cartón abierto, y crayones gruesos.',
    steps: [
      'Acuesten a {toy} sobre la hoja, y dibujá el contorno despacito.',
      'Saquen a {toy}, miren la forma y pregunten: “¿Quién es?”.',
      'Que {kid} pinte el retrato con los colores que quiera.',
    ],
    easier: 'Que {kid} haga garabatos adentro del contorno; no hace falta nada más.',
    harder: 'Que {kid} dibuje al lado algo que le encanta, como {interest}.',
  },
  {
    slug: 'la-orquesta',
    title: 'La orquesta de la cocina',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 12,
    maxAgeMonths: 47,
    energy: 'high',
    categories: ['create'],
    smallSpace: true,
    materials: ['un par de ollas o tuppers vacíos', 'dos cucharas de madera'],
    skills: ['ritmo', 'escuchar', 'causa y efecto'],
    safety: ['Ollas frías y vacías, y lejos de la cocina encendida.'],
    why: 'Un rato de ruido permitido: {kid} toca, vos acompañás, y después la casa queda más tranquila.',
    needs: 'un par de ollas o tuppers vacíos, y dos cucharas de madera.',
    steps: [
      'Den vuelta las ollas en el piso y repartan las cucharas.',
      'Toquen juntos: primero fuerte, después bajito, bajito.',
      'Cuando vos parás, {kid} para. Y arrancan de nuevo.',
    ],
    easier: 'Que {kid} toque como quiera, y vos acompañás con aplausos.',
    harder: 'Tocá un ritmo corto, tan-tan-tan, y que {kid} lo repita.',
  },
  {
    slug: 'una-torre',
    title: 'Una torre para {toy}',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 12,
    maxAgeMonths: 47,
    energy: 'medium',
    categories: ['create'],
    smallSpace: true,
    materials: ['vasos de plástico o tuppers'],
    skills: ['motricidad fina', 'equilibrio', 'causa y efecto'],
    safety: ['Solo plástico: nada de vidrio ni loza.'],
    why: 'Construir y tirar abajo es de lo más divertido a esta edad. Y arriba de todo, en el lugar de honor, va {toy}.',
    needs: 'unos vasos de plástico o tuppers, y {toy}.',
    steps: [
      'Apilen los vasos juntos, uno arriba del otro.',
      'Cuando la torre esté alta, pongan a {toy} arriba de todo.',
      'A la cuenta de tres, que {kid} la tire abajo. Y a construir de nuevo.',
    ],
    easier: 'Con dos o tres tuppers grandes alcanza para una torre.',
    harder: 'Que {kid} construya sin ayuda y cuente los pisos.',
  },
  {
    slug: 'la-casa-de-carton',
    title: 'La casa de {toy}',
    minutes: 25,
    place: 'indoor',
    minAgeMonths: 18,
    maxAgeMonths: 47,
    energy: 'low',
    categories: ['create', 'pretend'],
    smallSpace: true,
    materials: ['una caja de cartón', 'crayones gruesos', 'una tijera, solo para vos'],
    skills: ['creatividad', 'motricidad fina', 'juego simbólico'],
    safety: [
      'Sacale a la caja las grampas y la cinta de embalar antes de jugar.',
      'La tijera la usás vos, y después se guarda.',
    ],
    why: 'Con una caja vacía alcanza: {toy} se muda a una casa nueva, y {kid} la decora.',
    needs: 'una caja de cartón, crayones gruesos, una tijera y {toy}.',
    steps: [
      'Recortá en la caja una puerta y una ventana.',
      'Que {kid} pinte la casa por fuera: rayas, flores, lo que salga.',
      'Que {toy} entre por la puerta y se asome por la ventana a saludar.',
    ],
    easier: 'Sin recortar nada: la caja abierta ya es una casa.',
    harder: 'Que {kid} le arme a {toy} una cama adentro, con un repasador.',
  },
  {
    slug: 'el-camino',
    title: 'Un camino para {toy}',
    minutes: 15,
    place: 'indoor',
    minAgeMonths: 18,
    maxAgeMonths: 47,
    energy: 'medium',
    categories: ['create', 'pretend'],
    smallSpace: true,
    materials: ['cinta de papel'],
    skills: ['motricidad fina', 'planificar', 'juego simbólico'],
    safety: [
      'Cortá vos la cinta, y al terminar junten los pedacitos: no van a la boca.',
      'Mejor sobre baldosas o cerámica: en la madera, la cinta puede dejar marca.',
    ],
    why: 'Una tira de cinta en el piso se vuelve un camino, y {toy} tiene que llegar a algún lado. {kid} decide adónde.',
    needs: 'cinta de papel y {toy}.',
    steps: [
      'Pegá una tira larga de cinta en el piso, con curvas, y que {kid} te ayude a apretarla.',
      'Al final del camino, marquen una casita con un cuadrado de cinta.',
      'Que {kid} lleve a {toy} por el camino hasta la casita, sin salirse.',
    ],
    easier: 'Un camino recto y corto, de la mesa a la puerta.',
    harder: 'Agreguen un puente, que es un almohadón, y un túnel, que es una silla.',
  },

  // Batch 2: el cuerpo en movimiento (JUG-24).
  {
    slug: 'los-nenufares',
    title: 'De hoja en hoja',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 18,
    maxAgeMonths: 59,
    energy: 'high',
    categories: ['move'],
    smallSpace: true,
    materials: ['hojas de papel o repasadores'],
    skills: ['equilibrio', 'motricidad gruesa', 'seguir consignas'],
    safety: ['Sobre piso liso el papel resbala: usá repasadores, o jueguen sobre la alfombra.'],
    why: 'Saltar de hoja en hoja gasta energía sin salir del living, y con unos papeles alcanza.',
    needs: 'unas hojas de papel o repasadores, y un poco de piso libre.',
    steps: [
      'Repartan las hojas por el piso, separadas por un pasito.',
      'El piso de alrededor es agua: solo se pisa arriba de las hojas.',
      'Crucen los dos, saltando de hoja en hoja y haciendo “croac”.',
      'Cuando lleguen, sacá una hoja y vuelvan: ahora hay que saltar más lejos.',
    ],
    easier: 'Hojas bien juntas, y se cruza caminando y de la mano.',
    harder: 'Que {kid} arme el camino de hojas antes de cruzar.',
  },
  {
    slug: 'el-tunel-de-cajas',
    title: 'El túnel',
    minutes: 15,
    place: 'indoor',
    minAgeMonths: 12,
    maxAgeMonths: 47,
    energy: 'medium',
    categories: ['move', 'pretend'],
    smallSpace: true,
    materials: ['una caja grande'],
    skills: ['motricidad gruesa', 'noción del espacio', 'permanencia del objeto'],
    safety: [
      'Sacale a la caja las grampas y los ganchos antes de jugar.',
      'La caja se apoya en el piso: no se apila, y no se cierra con alguien adentro.',
    ],
    why: 'Gatear por un túnel es puro cuerpo, y del otro lado alguien espera. {toy} ya está del otro lado.',
    needs: 'una caja grande abierta de los dos lados, y {toy}.',
    steps: [
      'Abrí la caja de las dos puntas y apoyala en el piso: ese es el túnel.',
      'Poné a {toy} del otro lado, y ponete vos ahí también.',
      'Llamá a {kid} desde esa punta hasta que cruce el túnel.',
      'Festejen la llegada, y que {kid} lleve a {toy} de vuelta por adentro.',
    ],
    easier: 'Un túnel corto, y vos asomando la cara del otro lado todo el tiempo.',
    harder: 'Sumen una segunda caja para hacer el túnel más largo.',
  },
  {
    slug: 'la-sombra',
    title: 'Pisar la sombra',
    minutes: 10,
    place: 'outdoor',
    minAgeMonths: 24,
    maxAgeMonths: 71,
    energy: 'high',
    categories: ['move', 'explore'],
    smallSpace: false,
    materials: ['una tiza, si tenés'],
    skills: ['motricidad gruesa', 'observar', 'causa y efecto'],
    safety: ['Con sol fuerte, jueguen temprano o a la tarde, y con gorro.'],
    why: 'Con sol, la sombra sigue a {kid} a todos lados. Descubrir que se mueve con uno es un hallazgo.',
    needs: 'un día de sol y un pedazo de vereda o de plaza.',
    steps: [
      'Párense al sol y busquen las dos sombras en el piso.',
      'Muevan los brazos y miren qué hace cada sombra.',
      'Ahora corré a pisarle la sombra a {kid}, sin tocar a {kid}.',
      'Cambian: ahora {kid} corre atrás de tu sombra.',
    ],
    easier: 'Sin correr: saluden, salten y miren cómo la sombra hace lo mismo.',
    harder: 'Marquen el contorno de la sombra con una tiza, y vuelvan un rato después a ver si se movió.',
  },
  {
    slug: 'el-piso-es-lava',
    title: 'El piso es lava',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 36,
    maxAgeMonths: 71,
    energy: 'high',
    categories: ['move'],
    smallSpace: true,
    materials: ['almohadones', 'una manta'],
    skills: ['equilibrio', 'planificar', 'seguir consignas'],
    safety: [
      'Nada de subirse a sillas, mesas ni sillones: las islas van en el piso.',
      'Sobre piso liso los almohadones patinan: jueguen sobre alfombra, o apoyalos contra la pared.',
    ],
    why: 'A los tres o cuatro años el cuerpo pide moverse y la cabeza pide reglas. Este juego tiene las dos cosas.',
    needs: 'cuatro o cinco almohadones y una manta.',
    steps: [
      'Repartan los almohadones y la manta por el piso: esas son las islas.',
      'La regla es una sola: el piso es lava, y solo se pisa arriba de las islas.',
      'Crucen el living de isla en isla, pasando por todas.',
      'Cuando lleguen, sacá una isla y vuelvan a cruzar.',
      'Que {kid} decida dónde va la última isla, y crucen una vez más.',
    ],
    easier: 'Islas grandes y bien juntas, y se puede cruzar de la mano.',
    harder: 'Que {kid} cruce llevando algo en la mano sin que se caiga.',
  },
  {
    slug: 'estatuas',
    title: 'Estatuas',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 24,
    maxAgeMonths: 71,
    energy: 'high',
    categories: ['move'],
    smallSpace: true,
    materials: ['música'],
    skills: ['autocontrol', 'escuchar', 'motricidad gruesa'],
    safety: ['Despejen el piso antes de empezar, y ojo con las esquinas de la mesa.'],
    why: 'Bailar y frenar de golpe es de los primeros juegos donde hay que aguantarse las ganas, y {kid} quiere ganar esa pelea.',
    needs: 'música y un poco de lugar.',
    steps: [
      'Poné música y bailen juntos por el living.',
      'Cortá la música de golpe: los dos quedan como estatuas.',
      'El que se mueve primero hace una mueca, y arranca de nuevo la música.',
      'Después que {kid} maneje la música, y la estatua sos vos.',
    ],
    easier: 'Frená bien marcado, gritando “¡estatua!”, para que {kid} copie.',
    harder: 'Antes de cortar la música, digan cómo hay que quedarse: en una pata, bien bajito, o con los brazos arriba.',
  },
  {
    slug: 'la-mancha',
    title: 'La mancha en la plaza',
    minutes: 15,
    place: 'outdoor',
    minAgeMonths: 30,
    maxAgeMonths: 71,
    energy: 'high',
    categories: ['move'],
    smallSpace: false,
    materials: [],
    skills: ['motricidad gruesa', 'turnos', 'entender una regla'],
    safety: ['Elijan un pedazo de plaza lejos de la calle y de las hamacas en movimiento, y marquen hasta dónde se puede correr.'],
    why: 'La mancha es el juego de plaza de siempre, y a esta edad ya se entiende la regla: el que toca pasa a ser el que corre.',
    needs: 'nada más que la plaza y ganas de correr.',
    steps: [
      'Marquen con qué árboles se puede llegar: eso es la cancha.',
      'Elijan quién la queda primero, y cuenten hasta cinco para arrancar.',
      'El que la queda corre a tocar al otro, y ahí cambian.',
      'Cuando estén cansados, griten “¡pido!” y se para todo.',
    ],
    easier: 'Corré vos siempre, y dejate alcanzar seguido.',
    harder: 'Agreguen una casita: un árbol donde no se puede manchar, pero donde solo se para tres segundos.',
  },
  {
    slug: 'el-circuito',
    title: 'El circuito del living',
    minutes: 20,
    place: 'indoor',
    minAgeMonths: 36,
    maxAgeMonths: 71,
    energy: 'high',
    categories: ['move', 'create'],
    smallSpace: false,
    materials: ['almohadones', 'una silla', 'cinta de papel'],
    skills: ['planificar', 'motricidad gruesa', 'acordarse del orden'],
    safety: [
      'Nada de trepar a los muebles: la silla es para pasar por abajo.',
      'Cortá vos la cinta, y al terminar junten los pedacitos.',
    ],
    why: 'Armar el circuito es la mitad del juego. {kid} decide el orden, y después hay que acordarse de todo.',
    needs: 'unos almohadones, una silla, cinta de papel y lugar en el piso.',
    steps: [
      'Pegá una línea de cinta en el piso: ahí arranca y ahí termina.',
      'Armen tres postas con {kid}: pasar por abajo de la silla, saltar dos almohadones y dar una vuelta entera.',
      'Hacé vos el circuito primero, despacio, diciendo cada posta en voz alta.',
      'Ahora le toca a {kid}, y vos contás en voz alta cuánto tarda.',
      'Que {kid} cambie una posta por otra, y háganlo de nuevo.',
    ],
    easier: 'Dos postas, y las hacen juntos de la mano.',
    harder: 'Que {kid} arme el circuito entero y te lo explique antes de que lo hagas vos.',
  },

  // Batch 3: la plaza, la vereda y los mandados (JUG-24).
  {
    slug: 'la-lista-de-la-plaza',
    title: 'La lista de la plaza',
    minutes: 20,
    place: 'outdoor',
    minAgeMonths: 30,
    maxAgeMonths: 71,
    energy: 'medium',
    categories: ['explore', 'out_and_about'],
    smallSpace: false,
    materials: ['una bolsa o un balde'],
    skills: ['observar', 'clasificar', 'lenguaje'],
    safety: [
      'Nada va a la boca, y no se juntan hongos, semillas ni vidrios.',
      'Al volver, lávense las manos.',
    ],
    why: 'En la plaza hay de todo si uno sabe qué buscar. La lista le da a {kid} una misión, y el paseo dura el doble.',
    needs: 'una bolsa o un balde, y una plaza.',
    steps: [
      'Antes de salir, elijan cuatro cosas para buscar: algo áspero, algo celeste, algo más chico que un dedo y algo que haga ruido.',
      'Caminen despacio y busquen de a una, sin apuro.',
      'Cada cosa que aparece va a la bolsa, y {kid} cuenta por qué sirve.',
      'Al volver, vacíen la bolsa sobre la mesa y pongan todo en fila, de lo más chico a lo más grande.',
    ],
    easier: 'Dos cosas nada más, y bien fáciles: una hoja y una piedra.',
    harder: 'Que {kid} invente dos de las cosas de la lista antes de salir.',
  },
  {
    slug: 'la-rayuela',
    title: 'La rayuela',
    minutes: 15,
    place: 'outdoor',
    minAgeMonths: 36,
    maxAgeMonths: 71,
    energy: 'high',
    categories: ['move', 'learn'],
    smallSpace: false,
    materials: ['una tiza', 'una piedrita'],
    skills: ['equilibrio', 'contar', 'turnos'],
    safety: [
      'Dibujen en la vereda o en la plaza, lejos del cordón.',
      'La piedrita se tira al piso, nunca hacia arriba.',
    ],
    why: 'La rayuela es de toda la vida, y de paso {kid} salta, cuenta y espera el turno sin darse cuenta.',
    needs: 'una tiza, una piedrita y un pedazo de vereda.',
    steps: [
      'Dibujen con la tiza seis cuadrados numerados, en fila.',
      'Que {kid} tire la piedrita al primer cuadrado.',
      'Se salta hasta el final sin pisar el cuadrado de la piedrita, y se vuelve.',
      'A la vuelta, {kid} junta la piedrita, y el próximo tiro va al cuadrado que sigue.',
      'Cuando termine {kid}, tirás vos, y {kid} te avisa si pisás mal.',
    ],
    easier: 'Cuatro cuadrados, sin piedrita: alcanza con saltar y contar en voz alta.',
    harder: 'De ida en una pata, de vuelta con los dos pies.',
  },
  {
    slug: 'el-veo-veo',
    title: 'Veo veo',
    minutes: 10,
    place: 'outdoor',
    minAgeMonths: 36,
    maxAgeMonths: 71,
    energy: 'low',
    categories: ['out_and_about', 'learn', 'low_energy'],
    smallSpace: true,
    materials: [],
    skills: ['observar', 'lenguaje', 'turnos'],
    safety: [],
    why: 'Sirve para la cola del banco, el colectivo o la espera en la salita: no hace falta nada y se corta cuando quieran.',
    needs: 'nada, y sirve en cualquier lado.',
    steps: [
      'Arrancás vos: “Veo veo una cosa de color rojo”.',
      'Que {kid} mire alrededor y vaya diciendo qué puede ser.',
      'Si no sale, dale otra pista: dónde está, o para qué sirve.',
      'Cuando adivine, le toca elegir a {kid}, y adivinás vos.',
    ],
    easier: 'Elegí algo grande y que esté justo enfrente.',
    harder: 'En vez del color, la pista es para qué sirve: “Veo veo algo que sirve para sentarse”.',
  },
  {
    slug: 'el-mandado',
    title: 'El encargo de la verdulería',
    minutes: 15,
    place: 'outdoor',
    minAgeMonths: 36,
    maxAgeMonths: 71,
    energy: 'low',
    categories: ['out_and_about', 'helpers'],
    smallSpace: true,
    materials: ['una bolsa chica'],
    skills: ['memoria', 'contar', 'hablar con otros'],
    safety: ['En la vereda, {kid} camina del lado de adentro, y para cruzar siempre de la mano.'],
    why: 'El mandado deja de ser un trámite cuando {kid} tiene un encargo propio y una bolsa para traerlo.',
    needs: 'una bolsa chica y un mandado corto.',
    steps: [
      'Antes de salir, digan en voz alta el encargo: tres bananas y una zanahoria.',
      'Que {kid} lo repita hasta la esquina, para no olvidarse.',
      'En la verdulería, que {kid} pida el encargo y cuente las bananas mientras las ponen en la bolsa.',
      'La bolsa la lleva {kid} hasta casa, y la guarda en su lugar.',
    ],
    easier: 'Un solo encargo, y lo decís junto con {kid}.',
    harder: 'Tres encargos, y que {kid} se acuerde de los tres sin ayuda.',
  },
  {
    slug: 'el-camino-de-tiza',
    title: 'El camino de tiza',
    minutes: 15,
    place: 'outdoor',
    minAgeMonths: 24,
    maxAgeMonths: 59,
    energy: 'medium',
    categories: ['move', 'create'],
    smallSpace: false,
    materials: ['tizas'],
    skills: ['equilibrio', 'motricidad gruesa', 'seguir consignas'],
    safety: ['Dibujen en la vereda lejos del cordón, y con {kid} siempre del lado de adentro.'],
    why: 'Con una tiza, la vereda se convierte en un camino, y {kid} lo recorre veinte veces sin aburrirse.',
    needs: 'tizas y un pedazo de vereda.',
    steps: [
      'Dibujá una línea larga, con curvas y una parte en zigzag.',
      'Que {kid} la camine entera sin salirse, con los brazos abiertos.',
      'Agregá círculos al costado: ahí hay que saltar con los dos pies.',
      'Recorran el camino juntos, uno atrás del otro, cada vez más rápido.',
    ],
    easier: 'Una línea recta y gorda, y {kid} la camina de la mano.',
    harder: 'Que {kid} dibuje el próximo tramo y te diga cómo hay que pasarlo.',
  },
  {
    slug: 'las-hormigas',
    title: 'Seguir a las hormigas',
    minutes: 10,
    place: 'outdoor',
    minAgeMonths: 30,
    maxAgeMonths: 71,
    energy: 'low',
    categories: ['explore', 'low_energy'],
    smallSpace: true,
    materials: [],
    skills: ['observar', 'paciencia', 'lenguaje'],
    safety: [
      'Se mira y no se toca: las hormigas pican, y algunas plantas también.',
      'Al terminar, lávense las manos.',
    ],
    why: 'Una fila de hormigas entretiene más que cualquier juguete, y {kid} puede quedarse un rato largo mirándolas.',
    needs: 'nada más que un cantero o un árbol de la plaza.',
    steps: [
      'Busquen una fila de hormigas en el piso o en el tronco de un árbol.',
      'Agáchense y sigan la fila con el dedo en el aire, sin tocar.',
      'Busquen de dónde vienen y adónde van.',
      'Elijan un punto de la fila y cuenten en voz alta cuántas pasan hasta llegar a diez.',
    ],
    easier: 'Alcanza con encontrarlas y mirarlas un ratito.',
    harder: 'Que {kid} adivine qué están llevando, y busquen si hay otra fila cerca.',
  },

  // Batch 4: ayudar en casa, con tareas de verdad (JUG-24).
  {
    slug: 'las-medias-perdidas',
    title: 'Las medias perdidas',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 24,
    maxAgeMonths: 59,
    energy: 'low',
    categories: ['helpers', 'learn', 'low_energy'],
    smallSpace: true,
    materials: ['el canasto de la ropa limpia'],
    skills: ['clasificar', 'motricidad fina', 'atención'],
    safety: [],
    why: 'Hay que doblar la ropa igual, y de a dos se hace juego. Buscar la media que falta es un rompecabezas sin piezas.',
    needs: 'el canasto de la ropa limpia, sin doblar.',
    steps: [
      'Vacíen el canasto sobre la cama y saquen todas las medias.',
      'Poné una media sola en el medio y pedile a {kid} que busque la igual.',
      'Cuando aparezca, que {kid} las junte y las deje en una pila.',
      'Cuando no queden medias sueltas, {kid} lleva la pila al cajón.',
    ],
    easier: 'Tres pares nada más, y bien distintos entre sí.',
    harder: 'Que {kid} las ordene por dueño, y arme una pila para cada uno.',
  },
  {
    slug: 'poner-la-mesa',
    title: 'Poner la mesa',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 30,
    maxAgeMonths: 71,
    energy: 'low',
    categories: ['helpers', 'learn', 'low_energy'],
    smallSpace: true,
    materials: ['los platos y los cubiertos de la cena', 'servilletas'],
    skills: ['contar', 'uno para cada uno', 'terminar lo empezado'],
    safety: ['Los cuchillos los ponés vos: {kid} lleva servilletas, vasos de plástico y cucharas.'],
    why: 'Poner la mesa es contar sin darse cuenta: una servilleta por persona, un vaso por persona. Y queda hecho de verdad.',
    needs: 'las servilletas, los vasos y las cucharas de la cena.',
    steps: [
      'Cuenten juntos cuántos van a comer, y nombren a cada uno.',
      'Que {kid} lleve una servilleta por vez y deje una en cada lugar.',
      'Después los vasos, siempre de a uno, contando en voz alta.',
      'Al final, miren juntos si falta algo en algún lugar.',
    ],
    easier: 'Solo las servilletas, y vos le vas diciendo dónde va cada una.',
    harder: 'Que {kid} ponga la mesa entera y te avise cuando esté lista.',
  },
  {
    slug: 'lavar-la-verdura',
    title: 'El lavadero de verduras',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 24,
    maxAgeMonths: 59,
    energy: 'low',
    categories: ['helpers', 'low_energy'],
    smallSpace: true,
    materials: ['un bowl con agua', 'un repasador', 'verduras enteras'],
    skills: ['motricidad fina', 'seguir consignas', 'cuidar las cosas'],
    safety: [
      'Verduras enteras y grandes, nada cortado ni chiquito.',
      'El bowl va en una mesa baja, para que {kid} llegue de pie, sin subirse a nada.',
      'Poco agua, y no te alejes mientras {kid} esté con el bowl.',
    ],
    why: 'Lavar zanahorias con las manos en el agua engancha muchísimo a esta edad, y ayuda de verdad con la cena.',
    needs: 'un bowl con un dedo de agua, un repasador y unas verduras enteras.',
    steps: [
      'Poné el bowl con agua en una mesa baja, con el repasador al lado.',
      'Mostrale a {kid} cómo se frota una zanahoria con las dos manos.',
      'Que {kid} lave una por una y las vaya dejando sobre el repasador.',
      'Al final, séquenlas juntos y llévenlas a la cocina.',
    ],
    easier: 'Dos verduras grandes y fáciles de agarrar.',
    harder: 'Que {kid} las seque, las cuente y las guarde en la heladera.',
  },
  {
    slug: 'la-plantita',
    title: 'Una plantita de {kid}',
    minutes: 20,
    place: 'indoor',
    minAgeMonths: 36,
    maxAgeMonths: 71,
    energy: 'low',
    categories: ['helpers', 'explore'],
    smallSpace: true,
    materials: ['un vaso de yogur vacío', 'tierra', 'unas semillas o un poroto'],
    skills: ['paciencia', 'observar', 'hacerse cargo'],
    safety: [
      'Las semillas y los porotos no van a la boca, ni crudos ni remojados.',
      'Los agujeros del vaso los hacés vos, y después guardás la tijera.',
      'Al terminar, lávense las manos.',
    ],
    why: 'La planta es de {kid}, y hay que ir a verla todos los días. Esperar una semana a que salga algo es un ejercicio enorme.',
    needs: 'un vaso de yogur vacío, un poco de tierra y unas semillas o un poroto.',
    steps: [
      'Hacele al vaso dos agujeritos abajo, con la punta de una tijera.',
      'Que {kid} lo llene de tierra con una cuchara, hasta casi el borde.',
      'Hagan un pocito con el dedo, pongan la semilla y tápenla.',
      'Que {kid} le eche un chorrito de agua y lo lleve a una ventana.',
      'Cada mañana, vayan juntos a mirar si pasó algo.',
    ],
    easier: 'Llená vos el vaso, y que {kid} ponga la semilla y el agua.',
    harder: 'Que {kid} le haga un cartel con su nombre, y marque en un papel los días que pasaron.',
  },
  {
    slug: 'guardar-antes-de-que-suene',
    title: 'Guardar antes de que suene',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 30,
    maxAgeMonths: 71,
    energy: 'high',
    categories: ['helpers', 'move'],
    smallSpace: true,
    materials: ['un timer, o el celular', 'dos cajas o baldes'],
    skills: ['clasificar', 'terminar lo empezado', 'motricidad gruesa'],
    safety: ['Que nadie corra con cosas duras en la mano, y que las cajas no queden en el paso.'],
    why: 'Guardar es lo que menos gusta, y contra el reloj se vuelve una carrera. Termina con el piso despejado.',
    needs: 'un timer o el celular, y dos cajas o baldes.',
    steps: [
      'Miren juntos el desorden y pongan dos cajas en el medio: una para los juguetes y otra para lo que no lo es.',
      'Poné el timer en cinco minutos y mostrale el número a {kid}.',
      'Guarden los dos a la vez, cada uno llevando cosas a la caja que va.',
      'Cuando suene, frenen donde estén y miren cuánto quedó.',
      'Si falta poco, pongan dos minutos más y terminen.',
    ],
    easier: 'Una sola caja, y {kid} guarda solo los juguetes grandes.',
    harder: 'Que {kid} adivine antes cuántas cosas va a poder guardar, y después las cuenten.',
  },
  {
    slug: 'el-trapo-y-el-balde',
    title: 'El trapo y el balde',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 24,
    maxAgeMonths: 59,
    energy: 'medium',
    categories: ['helpers', 'move'],
    smallSpace: true,
    materials: ['un trapo o una esponja', 'un balde con agua'],
    skills: ['motricidad gruesa', 'cuidar las cosas', 'terminar lo empezado'],
    safety: [
      'Solo agua: los productos de limpieza quedan guardados y fuera del alcance.',
      'Sequen el piso al terminar, para que nadie resbale.',
    ],
    why: 'Limpiar en serio, con trapo y balde, es trabajo de grande, y a esta edad eso es lo mejor que hay.',
    needs: 'un trapo o una esponja, y un balde con un poco de agua.',
    steps: [
      'Elijan qué se va a limpiar: la puerta del placard, las sillas o las baldosas.',
      'Mostrale a {kid} cómo se moja el trapo y se escurre bien.',
      'Que {kid} pase el trapo de arriba hacia abajo, mientras vos hacés otra parte.',
      'Miren juntos cómo quedó, y guarden el balde y el trapo en su lugar.',
    ],
    easier: 'Una esponja apenas húmeda y una sola silla.',
    harder: 'Que {kid} elija tres cosas para limpiar y no pare hasta terminar las tres.',
  },

  // Batch 5: aprender jugando (JUG-24).
  {
    slug: 'el-intruso',
    title: 'El intruso',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 30,
    maxAgeMonths: 59,
    energy: 'low',
    categories: ['learn', 'low_energy'],
    smallSpace: true,
    materials: ['cuatro o cinco cosas de la casa'],
    skills: ['clasificar', 'lenguaje', 'atención'],
    safety: ['Nada de vidrio, ni cosas tan chicas que entren en la boca.'],
    why: 'Encontrar el que no va pide mirar, comparar y explicar por qué. Y se juega sentados, con lo que hay en la mesa.',
    needs: 'cuatro o cinco cosas parecidas entre sí, y una distinta.',
    steps: [
      'Juntá tres cosas de comer y una que no lo sea, y ponelas en fila.',
      'Preguntale a {kid}: “¿Cuál no va acá?”.',
      'Cuando elija una, que cuente por qué.',
      'Ahora la fila la arma {kid}, y adivinás vos.',
    ],
    easier: 'Tres cosas nada más, y que la distinta se note mucho.',
    harder: 'Que las cuatro sean del mismo tipo, y lo que cambia sea el color o el tamaño.',
  },
  {
    slug: 'el-ruido-escondido',
    title: 'El ruido escondido',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 18,
    maxAgeMonths: 59,
    energy: 'low',
    categories: ['learn', 'low_energy'],
    smallSpace: true,
    materials: ['tres o cuatro cosas de la cocina'],
    skills: ['escuchar', 'memoria', 'lenguaje'],
    safety: ['Nada de vidrio, y sonidos suaves: cerca de la oreja todo suena más fuerte.'],
    why: 'Con los ojos tapados, el oído hace todo el trabajo. Es tranquilo y sirve para bajar un cambio.',
    needs: 'tres o cuatro cosas que hagan ruido: una cuchara, un papel, un tupper.',
    steps: [
      'Mostrale a {kid} cada cosa y hagan juntos el ruido que hace.',
      'Que {kid} se tape los ojos con las manos.',
      'Hacé sonar una, y que {kid} adivine cuál fue.',
      'Cuando acierte varias, cambian: el ruido lo hace {kid} y adivinás vos.',
    ],
    easier: 'Dos cosas con ruidos bien distintos, y {kid} mira mientras las hacés.',
    harder: 'Hacé dos ruidos seguidos, y que {kid} diga cuál fue primero.',
  },
  {
    slug: 'frio-o-caliente',
    title: 'Frío, frío… caliente',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 30,
    maxAgeMonths: 71,
    energy: 'medium',
    categories: ['learn', 'move'],
    smallSpace: true,
    materials: [],
    skills: ['escuchar', 'noción del espacio', 'turnos'],
    safety: ['Escondan a la vista y en lugares bajos: nada de trepar, ni de meter la mano donde no se ve.'],
    why: 'Buscar guiado por la voz es escuchar de verdad. {toy} está escondido en algún lugar del living.',
    needs: '{toy} y un ambiente de la casa.',
    steps: [
      'Que {kid} espere en la puerta, tapándose los ojos.',
      'Escondé a {toy} en un lugar bajo, dejando una parte a la vista.',
      'Que {kid} empiece a buscar: vos decís “frío” cuando se aleja y “caliente” cuando se acerca.',
      'Cuando aparezca {toy}, festejen. Ahora le toca esconder a {kid}, y buscás vos.',
    ],
    easier: 'Escondé a {toy} casi a la vista, y decí “caliente” bien seguido.',
    harder: 'Que {kid} esconda a {toy} y te guíe solo con las palabras, sin señalar.',
  },
  {
    slug: 'cuantos-pasos',
    title: '¿Cuántos pasos?',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 36,
    maxAgeMonths: 71,
    energy: 'medium',
    categories: ['learn', 'move'],
    smallSpace: true,
    materials: [],
    skills: ['contar', 'medir', 'comparar'],
    safety: [],
    why: 'Medir la casa a pasos es contar con el cuerpo. Al final aparece la pregunta de por qué a vos te dan menos.',
    needs: 'nada más que la casa.',
    steps: [
      'Elijan un recorrido corto: de la puerta del baño a la cocina.',
      'Que {kid} lo camine contando los pasos en voz alta, y anotá el número.',
      'Ahora caminalo vos, contando, y comparen los dos números.',
      'Pregunten por qué a {kid} le dieron más pasos que a vos.',
      'Midan otro recorrido, y adivinen antes cuántos van a ser.',
    ],
    easier: 'Un recorrido de cinco o seis pasos, y contás en voz alta junto con {kid}.',
    harder: 'Midan con pasos de hormiga, talón contra punta, y comparen con los pasos normales.',
  },
  {
    slug: 'se-hunde-o-flota',
    title: '¿Se hunde o flota?',
    minutes: 20,
    place: 'indoor',
    minAgeMonths: 36,
    maxAgeMonths: 71,
    energy: 'low',
    categories: ['learn', 'explore'],
    smallSpace: true,
    materials: ['un balde o una palangana con agua', 'cosas de la casa que se puedan mojar'],
    skills: ['adivinar y comprobar', 'clasificar', 'lenguaje'],
    safety: [
      'Poco agua, y no te alejes mientras {kid} esté con el balde.',
      'Lejos de enchufes y de cosas con pilas.',
      'Vacíen el balde apenas terminen.',
    ],
    why: 'Adivinar primero y probar después: a veces {kid} acierta y a veces se sorprende, y las dos cosas están buenas.',
    needs: 'un balde con agua y seis cosas de la casa que se puedan mojar.',
    steps: [
      'Junten seis cosas: un corcho, una cuchara, una hoja, una piedra, un tupper y una tapita.',
      'Antes de probar, que {kid} diga de cada una si se va a hundir o a flotar.',
      'Prueben de a una, sin apuro, y miren qué pasa.',
      'Armen dos montoncitos al costado: las que flotaron y las que se hundieron.',
      'Miren los dos montones y busquen qué tienen en común.',
    ],
    easier: 'Tres cosas, y sin adivinar antes: alcanza con tirarlas y mirar.',
    harder: 'Que {kid} busque una cosa más de la casa y diga antes en qué montón va a terminar.',
  },
  {
    slug: 'el-memotest-casero',
    title: 'El memotest de la casa',
    minutes: 20,
    place: 'indoor',
    minAgeMonths: 36,
    maxAgeMonths: 71,
    energy: 'low',
    categories: ['learn', 'create', 'low_energy'],
    smallSpace: true,
    materials: ['cartón o papel grueso', 'crayones', 'una tijera, solo para vos'],
    skills: ['memoria', 'turnos', 'motricidad fina'],
    safety: ['La tijera la usás vos, y después se guarda.'],
    why: 'Primero se fabrica y después se juega, así que rinde doble. Y a esta edad {kid} le gana a cualquier grande.',
    needs: 'cartón, crayones y una tijera.',
    steps: [
      'Cortá doce cuadraditos de cartón, todos del mismo tamaño.',
      'Elijan seis dibujos fáciles, y que {kid} haga cada uno dos veces, en dos cartones.',
      'Den vuelta todos los cartones sobre la mesa y mézclenlos.',
      'Por turnos, cada uno da vuelta dos: si son iguales se los lleva, y si no, los deja donde estaban.',
      'Cuando no quede ninguno, cuenten quién juntó más pares.',
    ],
    easier: 'Ocho cartones y cuatro dibujos, y se juega con todos a la vista.',
    harder: 'Sumen dos pares más, con cosas que le encantan a {kid}, como {interest}.',
  },
  {
    slug: 'la-caza-del-color',
    title: 'La caza del color',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 24,
    maxAgeMonths: 59,
    energy: 'medium',
    categories: ['learn', 'move'],
    smallSpace: true,
    materials: ['un repasador'],
    skills: ['colores', 'clasificar', 'motricidad gruesa'],
    safety: ['Nada de vidrio, ni cosas tan chicas que entren en la boca.'],
    why: 'Buscar todo lo rojo de la casa hace que {kid} mire de nuevo cosas que ve todos los días.',
    needs: 'un repasador, y la casa.',
    steps: [
      'Poné el repasador en el piso: todo lo que se junte va ahí.',
      'Digan el color en voz alta y salgan a buscar por la casa.',
      'Cada cosa que aparece va al repasador, y {kid} dice qué es.',
      'Cuando junten cinco, cuéntenlas y elijan otro color.',
    ],
    easier: 'Un solo color, y señalás la primera cosa para arrancar.',
    harder: 'Dos repasadores de colores distintos, y cada cosa va en el que le toca.',
  },

  // Batch 6: proyectos largos, de varios pasos, para los más grandes (JUG-24).
  {
    slug: 'la-ciudad-de-carton',
    title: 'Una ciudad de cartón',
    minutes: 30,
    place: 'indoor',
    minAgeMonths: 36,
    maxAgeMonths: 71,
    energy: 'low',
    categories: ['create', 'pretend'],
    smallSpace: false,
    materials: ['cajas chicas y tubos de cartón', 'crayones', 'cinta de papel', 'una tijera, solo para vos'],
    skills: ['planificar', 'creatividad', 'juego simbólico'],
    safety: [
      'Sacales a las cajas las grampas y la cinta de embalar antes de empezar.',
      'La tijera la usás vos, y después se guarda.',
    ],
    why: 'Una ciudad no se termina: cada edificio pide otro. Empieza hoy y sigue mañana en el mismo rincón.',
    needs: 'cajas de fideos o de té, tubos de cartón, crayones, cinta y {toy}.',
    steps: [
      'Despejen un rincón del piso: ahí va a vivir la ciudad, y nadie la levanta hasta mañana.',
      'Pongan las cajas paradas: esos son los edificios, y {kid} decide cuál es cuál.',
      'Que {kid} les dibuje puertas y ventanas con los crayones.',
      'Hagan las calles con tiras de cinta pegadas al piso, entre los edificios.',
      'Que {toy} recorra la ciudad para conocer el barrio, y elija en qué edificio se queda.',
      'Elijan qué falta para mañana: una plaza, un puente, un almacén.',
    ],
    easier: 'Tres edificios y una sola calle, sin dibujar nada.',
    harder: 'Que {kid} le ponga nombre a cada calle y te explique cómo se llega de un edificio al otro.',
  },
  {
    slug: 'los-binoculares',
    title: 'Binoculares de cartón',
    minutes: 20,
    place: 'indoor',
    minAgeMonths: 36,
    maxAgeMonths: 71,
    energy: 'medium',
    categories: ['create', 'explore'],
    smallSpace: true,
    materials: ['dos tubos de cartón', 'cinta de papel', 'crayones', 'un cordón corto'],
    skills: ['motricidad fina', 'observar', 'creatividad'],
    safety: [
      'El cordón se usa solo mientras jugás con {kid}, y después se guarda: nunca queda colgado al alcance.',
      'No se mira al sol con los binoculares.',
    ],
    why: 'Primero se fabrican y después sirven para algo. Con los binoculares puestos, la ventana de casa es una expedición.',
    needs: 'dos tubos de cartón, cinta, crayones y un cordón corto.',
    steps: [
      'Pongan los dos tubos juntos, y que {kid} los una con vueltas de cinta.',
      'Que {kid} los pinte con los crayones, como quiera.',
      'Atá el cordón de un lado al otro, del largo justo para colgarlos del cuello.',
      'Salgan a la ventana o al balcón y busquen tres cosas de un mismo color.',
      'Que {kid} avise cada vez que encuentra algo, y le pongan nombre a lo que ven.',
    ],
    easier: 'Un solo tubo, como un catalejo, y a mirar.',
    harder: 'Antes de asomarse, armen una lista de cinco cosas para buscar.',
  },
  {
    slug: 'el-titere-de-media',
    title: 'El títere de media',
    minutes: 25,
    place: 'indoor',
    minAgeMonths: 36,
    maxAgeMonths: 71,
    energy: 'low',
    categories: ['create', 'pretend'],
    smallSpace: true,
    materials: ['una media vieja', 'marcadores', 'papel y cinta de papel'],
    skills: ['creatividad', 'lenguaje', 'juego simbólico'],
    safety: ['La cara va dibujada: nada de botones ni cuentas pegadas, sobre todo si hay hermanos más chicos.'],
    why: 'Una media vieja se convierte en un personaje, y después ese personaje habla. {kid} le pone la voz.',
    needs: 'una media vieja, marcadores, papel y cinta.',
    steps: [
      'Ponete la media en la mano y mostrale a {kid} cómo abre y cierra la boca.',
      'Que {kid} le dibuje los ojos y la boca con los marcadores.',
      'Recorten orejas o pelo de papel, y péguenlos con cinta.',
      'Que {kid} le ponga un nombre y decida cómo habla: grave, agudo, despacio.',
      'Hagan una función corta atrás del respaldo del sillón, para quien esté en casa.',
    ],
    easier: 'La cara la dibujás vos, y {kid} elige el nombre y la voz.',
    harder: 'Hagan dos títeres, uno cada uno, y que conversen.',
  },
  {
    slug: 'la-masa-y-la-pizzeria',
    title: 'La masa y la pizzería',
    minutes: 25,
    place: 'indoor',
    minAgeMonths: 30,
    maxAgeMonths: 71,
    energy: 'low',
    categories: ['create', 'pretend'],
    smallSpace: true,
    materials: ['harina', 'sal', 'agua', 'un bowl', 'dos platos'],
    skills: ['motricidad fina', 'juego simbólico', 'contar'],
    safety: [
      'La masa de sal no se come: dejalo dicho antes de empezar.',
      'La cocina queda apagada: esto es solo amasar.',
      'Al terminar, lávense las manos.',
    ],
    why: 'Amasar fortalece la mano para cuando llegue el lápiz. Después la masa se convierte en pizzas, y la casa en una pizzería.',
    needs: 'dos tazas de harina, media taza de sal, un poco de agua, un bowl y dos platos.',
    steps: [
      'Que {kid} eche en el bowl las dos tazas de harina, contando cada una en voz alta.',
      'Sumen la sal y el agua de a poquito, mientras mezclan los dos.',
      'Amasen hasta que quede una masa que no se pegue en las manos.',
      'Que {kid} haga pizzas, ñoquis y lo que se le ocurra, y los ponga en los platos.',
      'Ahora la casa es una pizzería: entrás vos y pedís algo, y {kid} lo prepara, lo sirve y lo cobra con un aplauso.',
      'Guarden la masa en un tupper, para mañana.',
    ],
    easier: 'Medís vos, y {kid} mezcla y amasa. Bollitos aplastados con la palma ya son pizzas.',
    harder: 'Que {kid} tome el pedido, lo repita en voz alta y prepare dos cosas distintas.',
  },
  {
    slug: 'el-mural',
    title: 'El mural de la pared',
    minutes: 20,
    place: 'indoor',
    minAgeMonths: 24,
    maxAgeMonths: 59,
    energy: 'medium',
    categories: ['create'],
    smallSpace: true,
    materials: ['papel grande o una caja abierta', 'cinta de papel', 'crayones gruesos'],
    skills: ['motricidad gruesa', 'creatividad', 'motricidad fina'],
    safety: [
      'Usá cinta de papel, que sale sin llevarse la pintura de la pared.',
      'Con los más chicos, atentos a que los crayones no vayan a la boca.',
    ],
    why: 'Dibujar parado y en grande usa todo el brazo, no solo la mano. Y la hoja no se termina nunca.',
    needs: 'papel grande o una caja abierta, cinta de papel y crayones gruesos.',
    steps: [
      'Pegá el papel en la pared, a la altura de {kid}, con cinta en las cuatro puntas.',
      'Que {kid} dibuje de pie, con el brazo suelto, todo lo que quiera.',
      'Cuando frene, pedile que te cuente qué hay en el mural.',
      'Agregá vos algo chiquito en un rincón, y que {kid} lo busque.',
    ],
    easier: 'Un papel más chico y a la altura de la panza, para llegar sin estirarse.',
    harder: 'Que {kid} dibuje algo que le encanta, como {interest}, y le ponga alrededor todo lo que va con eso.',
  },
  {
    slug: 'el-libro-de-lo-que-me-gusta',
    title: 'El libro de {kid}',
    minutes: 25,
    place: 'indoor',
    minAgeMonths: 36,
    maxAgeMonths: 71,
    energy: 'low',
    categories: ['create', 'learn', 'low_energy'],
    smallSpace: true,
    materials: ['cuatro o cinco hojas', 'crayones', 'cinta de papel'],
    skills: ['lenguaje', 'reconocer su nombre', 'creatividad'],
    safety: [],
    why: 'Un libro sobre lo que a {kid} le gusta, hecho por {kid}. Se lee muchas veces, y en la tapa va su nombre.',
    needs: 'cuatro o cinco hojas, crayones y cinta de papel.',
    steps: [
      'Pregunten juntos cuáles son las cuatro cosas favoritas de {kid}, y anotalas.',
      'Una hoja para cada una: que {kid} dibuje, y vos escribís abajo lo que te dicte.',
      'En la tapa va el nombre de {kid}, con letras grandes.',
      'Junten las hojas y péguenlas de un lado con cinta, como el lomo de un libro.',
      'Léanlo juntos de punta a punta, y que {kid} cuente cada página.',
    ],
    easier: 'Dos páginas, y escribís vos todo mientras {kid} dibuja.',
    harder: 'Que {kid} copie su nombre en la tapa, y agreguen una página por día.',
  },
  {
    slug: 'los-aviones-de-papel',
    title: 'Aviones de papel',
    minutes: 15,
    place: 'indoor',
    minAgeMonths: 42,
    maxAgeMonths: 71,
    energy: 'medium',
    categories: ['create', 'move'],
    smallSpace: false,
    materials: ['hojas de papel', 'cinta de papel'],
    skills: ['motricidad fina', 'seguir pasos', 'comparar'],
    safety: ['Los aviones se tiran al pasillo, nunca a la cara ni cerca de los ojos.'],
    why: 'Doblar un avión son cuatro pasos exactos. A esta edad, seguirlos y que después vuele es un triunfo.',
    needs: 'unas hojas de papel y cinta de papel.',
    steps: [
      'Doblá vos uno primero, despacio, diciendo cada doblez en voz alta.',
      'Que {kid} doble el suyo copiándote, y ayudá solo en los dobleces difíciles.',
      'Pegá una tira de cinta en el piso del pasillo: esa es la línea de despegue.',
      'Tiren los dos desde ahí, y marquen con cinta dónde cayó cada avión.',
      'Prueben de nuevo cambiando algo: tirar más fuerte, más alto, o doblarle la punta.',
    ],
    easier: 'Que {kid} haga un bollo de papel y lo tire: también vuela, y se marca igual.',
    harder: 'Pongan un balde en el pasillo, y traten de embocar desde la línea.',
  },

  // Batch 7: para bajar un cambio (JUG-24).
  {
    slug: 'el-frasco-de-la-calma',
    title: 'El frasco de la calma',
    minutes: 15,
    place: 'indoor',
    minAgeMonths: 30,
    maxAgeMonths: 71,
    energy: 'low',
    categories: ['create', 'low_energy'],
    smallSpace: true,
    materials: ['una botella de plástico chica con tapa', 'agua tibia', 'brillantina o papelitos', 'cinta de embalar'],
    skills: ['calmarse', 'observar', 'paciencia'],
    safety: [
      'Botella de plástico, nunca de vidrio.',
      'Cerrá la tapa con muchas vueltas de cinta de embalar, para que no se abra.',
    ],
    why: 'Se arma una vez y sirve muchas: cuando {kid} explota, el frasco da algo para mirar mientras se le pasa.',
    needs: 'una botella de plástico chica, agua tibia, brillantina o papelitos, y cinta.',
    steps: [
      'Llená la botella casi hasta arriba con agua tibia.',
      'Que {kid} eche la brillantina o los papelitos, un poco por vez.',
      'Cerrá la tapa y dale muchas vueltas de cinta.',
      'Sacúdanla juntos y miren cómo baja todo, sin hablar, hasta que se asiente.',
      'Déjenla en un lugar fijo, para ir a buscarla cuando haga falta.',
    ],
    easier: 'Sacúdanla y miren un rato: no hace falta esperar hasta el final.',
    harder: 'Que {kid} respire hondo y despacio mientras baja la brillantina, y cuenten cuántas respiraciones tarda.',
  },
  {
    slug: 'sombras-en-la-pared',
    title: 'Sombras en la pared',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 24,
    maxAgeMonths: 71,
    energy: 'low',
    categories: ['low_energy', 'pretend'],
    smallSpace: true,
    materials: ['una linterna, o la luz del celular'],
    skills: ['imaginación', 'lenguaje', 'motricidad fina'],
    safety: ['No se apunta la luz a los ojos de nadie.'],
    why: 'Con la luz apagada y una linterna, la pared del cuarto se vuelve un teatro. Buen último juego antes de dormir.',
    needs: 'una linterna, o la luz del celular, y una pared lisa.',
    steps: [
      'Apaguen la luz y apunten la linterna a la pared.',
      'Hacé con la mano un perro que abre la boca, y que {kid} lo haga ladrar.',
      'Que {kid} invente una sombra con las manos, y adiviná vos qué es.',
      'Cuenten entre los dos una historia cortita con las dos sombras, que termine con las sombras yéndose a dormir.',
    ],
    easier: 'Muevan la mano y miren cómo la sombra crece y se achica: con eso alcanza.',
    harder: 'Que {kid} haga la sombra con {toy}, y arme la historia entera.',
  },
  {
    slug: 'la-pizza-en-la-espalda',
    title: 'La pizza en la espalda',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 24,
    maxAgeMonths: 71,
    energy: 'low',
    categories: ['low_energy'],
    smallSpace: true,
    materials: [],
    skills: ['calmarse', 'lenguaje', 'partes del cuerpo'],
    safety: ['Siempre suave, y si {kid} dice que no quiere, se para.'],
    why: 'Un masaje contado como una receta baja el ruido del día. Va bien después del baño, antes del cuento.',
    needs: 'nada más que la cama y las manos.',
    steps: [
      'Que {kid} se acueste boca abajo, y sentate al lado.',
      'Amasá la espalda con las palmas: “Primero amasamos la masa”.',
      'Pasá la salsa con la mano abierta, y espolvoreá el queso con los dedos, despacito.',
      'Pregunten qué más lleva, y que lo elija {kid}.',
      'Al final, la pizza va al horno: apoyá las dos manos quietas y contá hasta diez.',
    ],
    easier: 'Solo amasar y espolvorear, sin contar la receta entera.',
    harder: 'Ahora la pizza la hace {kid} en tu espalda, y los ingredientes los elegís vos.',
  },
  {
    slug: 'el-globo-que-se-infla',
    title: 'El globo que se infla',
    minutes: 5,
    place: 'indoor',
    minAgeMonths: 30,
    maxAgeMonths: 71,
    energy: 'low',
    categories: ['low_energy'],
    smallSpace: true,
    materials: [],
    skills: ['calmarse', 'respirar', 'imitación'],
    safety: [],
    why: 'Cinco minutos para cuando a {kid} se le sube todo. Inflarse y desinflarse da algo concreto que hacer con el cuerpo.',
    needs: 'nada, y sirve en cualquier lado.',
    steps: [
      'Siéntense en el piso, uno frente al otro, con las manos en la panza.',
      'Inflen el globo: aire por la nariz mientras los brazos se abren, contando hasta tres.',
      'Desínflenlo: aire por la boca, bien despacio, con un “ffff” largo, hasta quedar hechos un bollito.',
      'Háganlo tres veces, cada vez más lento.',
    ],
    easier: 'Una sola vez, y exagerás el ruido para que {kid} copie.',
    harder: 'Que {kid} elija de qué color es el globo y cuántas veces se infla.',
  },
  {
    slug: 'el-cuento-sin-leer',
    title: 'El cuento sin leer',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 18,
    maxAgeMonths: 59,
    energy: 'low',
    categories: ['low_energy', 'learn'],
    smallSpace: true,
    materials: ['un libro con dibujos'],
    skills: ['lenguaje', 'contar lo que pasa', 'imaginación'],
    safety: [],
    why: 'Antes de leerlo, se recorre mirando. {kid} cuenta lo que ve, y después el cuento se entiende mejor.',
    needs: 'un libro con dibujos, mejor si es nuevo para {kid}.',
    steps: [
      'Miren la tapa y pregunten de qué les parece que va a ser.',
      'Pasen las hojas sin leer una palabra, mirando solo los dibujos.',
      'En cada página, preguntá: “¿Qué está pasando acá?”, y que conteste {kid}.',
      'Al final, vuelvan al principio, y ahora sí, léanlo.',
    ],
    easier: 'Tres o cuatro páginas alcanzan, y señalás vos lo que hay para nombrar.',
    harder: 'Que {kid} cuente el cuento entero de memoria antes de que lo leas.',
  },

  // Batch 8: los juegos de siempre (JUG-24).
  {
    slug: 'la-gallinita-ciega',
    title: 'La gallinita ciega',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 36,
    maxAgeMonths: 71,
    energy: 'medium',
    categories: ['move'],
    smallSpace: true,
    materials: ['un pañuelo o un repasador'],
    skills: ['escuchar', 'noción del espacio', 'turnos'],
    safety: [
      'Despejen el piso y jueguen lejos de las esquinas de la mesa.',
      'Con los ojos tapados se camina, nunca se corre.',
    ],
    why: 'Un juego de siempre, y el primero donde {kid} descubre que se puede encontrar a alguien solo por el ruido.',
    needs: 'un pañuelo o un repasador, y un poco de lugar.',
    steps: [
      'Tapate vos los ojos con el pañuelo y date tres vueltas.',
      'Que {kid} se mueva por el living haciendo ruiditos, sin salir del ambiente.',
      'Caminá despacio, con las manos adelante, siguiendo el ruido, hasta dar con {kid}.',
      'Ahora los ojos tapados los tiene {kid}, y el ruido lo hacés vos.',
    ],
    easier: 'Que {kid} se quede en un solo lugar y aplauda hasta que llegues.',
    harder: 'Al encontrar a {kid}, adiviná con las manos en qué posición quedó: en cuclillas, de rodillas o con los brazos arriba.',
  },
  {
    slug: 'anton-pirulero',
    title: 'Antón Pirulero',
    minutes: 10,
    place: 'indoor',
    minAgeMonths: 36,
    maxAgeMonths: 71,
    energy: 'medium',
    categories: ['move', 'learn'],
    smallSpace: true,
    materials: [],
    skills: ['atención', 'ritmo', 'imitación'],
    safety: [],
    why: 'La canción de siempre, y adentro un juego difícil: hay que estar atento y hacer lo tuyo justo cuando toca.',
    needs: 'nada más que la canción.',
    steps: [
      'Cada uno elige un instrumento y lo hace con las manos: la guitarra, el tambor, la trompeta.',
      'Canten juntos: “Antón, Antón, Antón Pirulero, cada cual, cada cual, atiende su juego”.',
      'Mientras cantan, cada uno toca lo suyo, sin parar.',
      'Al llegar a “y el que no, y el que no, una prenda tendrá”, frenan los dos, y el último que se mueve hace una mueca.',
      'Cambien de instrumento y canten de nuevo.',
    ],
    easier: 'Un solo instrumento para los dos, y cantan y tocan juntos.',
    harder: 'Cambien de instrumento en el medio de la canción, sin avisar.',
  },
]
